export const categories = [
  "algebraic manipulation",
  "arithmetic operations",
  "arithmetic progression",
  "bearings",
  "bounds",
  "circle theorems",
  "complex numbers",
  "congruence and similarity",
  "coordinate geometry",
  "differentiation",
  "distributions",
  "expansions",
  "exponents and logarithms",
  "function modeling",
  "functions",
  "geometric progression",
  "graphs",
  "identities",
  "integration",
  "interests and depreciation",
  "kinematics",
  "limits",
  "linear algebra",
  "polynomials",
  "probability",
  "probability diagrams",
  "proof by contradiction",
  "proof by induction",
  "proofs",
  "series",
  "simultaneous equations",
  "solving equations",
  "special functions",
  "statistics",
  "transformation",
  "trigonometry",
  "vectors",
  "physics",
  "chemistry",
  "biology",
  "others",
];
